stages:
  - sync
  - check
  - prepare
  - build
  - compose
  - deploy

default:
  image:
    name: node:12-alpine
    entrypoint: [""]
  # All jobs are interruptible by default
  interruptible: true

workflow:
  rules:
    # If `$FORCE_GITLAB_CI` is set, create a pipeline.
    - if: "$FORCE_GITLAB_CI"
    - if: $CI_COMMIT_TAG
    # For `master` branch, don't create a pipeline.
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
      when: never
      # For other branches, create a pipeline.
    - if: $CI_COMMIT_BRANCH

variables:
  DOCKER_CONF: '{"auths":{"$CI_REGISTRY":{"username":"$CI_REGISTRY_USER","password":"$CI_REGISTRY_PASSWORD"}}}'
  KANIKO_PATH: .gitlab/kaniko
  GIT_CLONE_PATH: $CI_BUILDS_DIR/$CI_CONCURRENT_PROJECT_ID/$CI_PROJECT_PATH
  GIT_DEPTH: 10

include:
  - local: ".gitlab/ci/global.gitlab-ci.yml"
  - local: ".gitlab/ci/rules.gitlab-ci.yml"
  - local: ".gitlab/ci/sync.gitlab-ci.yml"
  - local: ".gitlab/ci/check.gitlab-ci.yml"
  - local: ".gitlab/ci/prepare.gitlab-ci.yml"
  - local: ".gitlab/ci/build.gitlab-ci.yml"
  - local: ".gitlab/ci/compose.gitlab-ci.yml"
  - local: ".gitlab/ci/deploy.gitlab-ci.yml"
  - local: ".gitlab/ci/local.gitlab-ci.yml"
