stages:
  - build

build_image:
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  before_script:
    - yum install nodejs10
    - npm install -g typescript
    - yarn install --production
    - tsc -b packages/common packages/server
    - yarn --cwd packages/web next build
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/packages/server/Dockerfile --destination $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_TAG
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/packages/web/Dockerfile --destination $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_TAG
  only:
    - tags
