default:
  image:
    name: node:latest
    entrypoint: [""]

stages:
  - prepare
  - build
  - deploy

.default-cache: &default-cache
  cache:
    key: "$CI_PROJECT_ID"
    untracked: true
    paths:
      - .yarn-cache
      - packages/*/dist
      - packages/web/.next

.default-artifacts: &default-artifacts
  artifacts:
    paths:
      - node_modules
      - packages/*/node_modules

install dev-dependencies:
  stage: prepare
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn-cache
  <<: *default-cache # Merge the contents of the 'default-cache' alias
  <<: *default-artifacts

install dependencies:
  stage: prepare
  script:
    - yarn install --frozen-lockfile --cache-folder .yarn-cache
  <<: *default-cache
  <<: *default-artifacts

compile packages:
  stage: build
  before_script:
    - npm install -g typescript
  script:
    - tsc -b packages/common packages/server
    - yarn --cwd packages/web next build
  dependencies:
    - install dev-dependencies
  artifacts:
    paths:
      - packages/common/dist
      - packages/server/dist
      - packages/web/.next
    untracked: false
    expire_in: 5 mins

build image:
  stage: deploy
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/packages/server/Dockerfile --destination $CI_REGISTRY_IMAGE/backend:$CI_COMMIT_TAG
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/packages/web/Dockerfile --destination $CI_REGISTRY_IMAGE/frontend:$CI_COMMIT_TAG
  dependencies:
    - install dependencies
    - compile packages
  only:
    - tags
    - web
