version: "3.3"

services:
  backend:
    build:
      context: .
      dockerfile: ./packages/server/Dockerfile
    environment:
      - FRONTEND_URI_DOCKER=frontend:3000
      - BACKEND_URI_DOCKER=backend:4000
      - NODE_ENV=production
    expose:
      - 4000
    volumes:
      - ~/Library/Caches/Yarn/v6:/yarn
    depends_on:
      - postgresql
      - redis

  frontend:
    build:
      context: .
      dockerfile: ./packages/web/Dockerfile
    # environment:
    #   - BACKEND_URI_DOCKER=backend:4000
    #   - BACKEND_URI=localhost:8080/api
    #   - NODE_ENV=production
    expose:
      - 3000
    volumes:
      - ~/Library/Caches/Yarn/v6:/yarn
    depends_on:
      - backend

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - backend
      - frontend

  redis:
    image: redis:alpine
    expose:
      - 6379

  postgresql:
    image: postgres
    expose:
      - 5432
    environment:
      POSTGRES_DB: stackflow
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
