.deploy:kaniko:build-image:
  stage: deploy
  extends: .global:base:kaniko
  environment:
    name: production
  script:
    - chmod +x scripts/setup-env.sh
    - . scripts/setup-env.sh
    - /kaniko/executor
      --context $CI_PROJECT_DIR
      --dockerfile $DOCKERFILE
      --destination $CI_REGISTRY_IMAGE/$IMAGE:$CI_COMMIT_TAG
      --cache=true
      --cache-ttl=9h
  needs:
    # extend job needs by overwriting global:base:kaniko's needs
    - job: compose packages and dependencies
      artifacts: true
    - job: compile packages
      artifacts: true
  # only:
  #   - tags

build backend:
  extends: .deploy:kaniko:build-image
  variables:
    IMAGE: "backend"
    DOCKERFILE: $CI_PROJECT_DIR/.gitlab/kaniko/build-backend.Dockerfile

build frontend:
  extends: .deploy:kaniko:build-image
  variables:
    IMAGE: "frontend"
    DOCKERFILE: $CI_PROJECT_DIR/.gitlab/kaniko/build-frontend.Dockerfile
