dont-interrupt-me:
  extends: .sync:rules:dont-interrupt-me
  stage: sync
  image: alpine:edge
  interruptible: false
  script:
    - echo "This jobs makes sure this pipeline won't be interrupted! See https://docs.gitlab.com/ee/ci/yaml/#interruptible."
